/** §1.3 / §8 Boughs — biome floors of the tree. Index 1 (Trunk) is open at start. */
import type { BandDef } from '../types'

export const bands: BandDef[] = [
  { id: 'trunk', index: 1, name: 'Trunk', line: 0, glyph: '🌳', direction: 'up', limbSlots: 0,
    sky: ['#3a4a52', '#7d8f86'], leaf: '#5aa653', ambient: ['🦋', '🐦'],
    drops: [{ id: 'bark', weight: 1 }],
    landmarkSlots: ['lm_bridge', 'lm_birdhouse', 'lm_flags', 'lm_door'],
    desc: 'Grey-green mist, a bare stump and one campfire. The Kiln sits at the stump; the Sawmill hook appears at 20 m, the Beamworks at 40 m.' },
  { id: 'roots', index: 2, name: 'Roots', line: 30, glyph: '🍄', direction: 'down', limbSlots: 2,
    ritual: { cost: { plank: 40, resin: 20 } },
    sky: ['#14100f', '#2b1f2e'], leaf: '#7dd3a8', ambient: ['🐛', '🐌'],
    drops: [{ id: 'stone', weight: 3 }, { id: 'bark', weight: 1 }],
    landmarkSlots: ['lm_mushrooms'],
    desc: 'The camera dips below the stump: dark loam, glow-mushrooms and pale stone. Diggers, the Brickyard and the Glasshouse live here.' },
  { id: 'canopy', index: 3, name: 'Canopy', line: 60, glyph: '🍃', direction: 'up', limbSlots: 3,
    ritual: { cost: { plank: 300, beam: 80 } },
    sky: ['#f4b860', '#8fbf7f'], leaf: '#6cc04a', ambient: ['🐦', '🐝', '🦋'],
    drops: [{ id: 'fiber', weight: 3 }, { id: 'honey', weight: 1 }],
    landmarkSlots: ['lm_owl', 'lm_swing'],
    desc: 'The sky crossfades to dappled gold; leaves and circling birds. Weavers, the Ropewalk at 80 m, the Lacquery at 120 m and the first limbs.' },
  { id: 'upper', index: 4, name: 'Upper Trunk', line: 200, glyph: '🌉', direction: 'up', limbSlots: 3,
    ritual: { cost: { beam: 600, brick: 300, glass: 120 } },
    sky: ['#5b4a7a', '#b8a6c9'], leaf: '#8fbf5a', ambient: ['🕊️', '🦋'],
    drops: [{ id: 'fiber', weight: 2 }, { id: 'bark', weight: 1 }, { id: 'honey', weight: 1 }],
    landmarkSlots: ['lm_chimes', 'lm_hammock'],
    desc: 'Mist turns grey-lavender; rope bridges run between limbs and the first lantern strings glow. The Lanternry at 250 m, the Amber Vault at 300 m, the Kite Yard.' },
  { id: 'deeproots', index: 5, name: 'Deep Roots', line: 400, glyph: '💎', direction: 'down', limbSlots: 2,
    ritual: { cost: { beam: 2000, glass: 600, lacquer: 300 } },
    sky: ['#06121f', '#123a4f'], leaf: '#5fd6d0', ambient: ['🦇', '🐛'],
    drops: [{ id: 'ore', weight: 3 }, { id: 'stone', weight: 2 }],
    landmarkSlots: ['lm_bell'],
    desc: 'The roots plunge deeper: ore veins, crystal glints and blue cave light. Miners and the Forge.' },
  { id: 'crown', index: 6, name: 'Crown', line: 800, glyph: '👑', direction: 'up', limbSlots: 3,
    ritual: { cost: { lantern: 2000, ingot: 500, lacquer: 1000 } },
    sky: ['#6fb7e6', '#e8f4fb'], leaf: '#9ad65e', ambient: ['🪁', '☁️', '🦅'],
    drops: [{ id: 'honey', weight: 2 }, { id: 'fiber', weight: 2 }],
    desc: 'Cloud-white and blue, wind streaks and drifting kites. The Clockworks at 1,000 m, the Weathervane, and the first Falling Stars.' },
  { id: 'cloudreach', index: 7, name: 'Cloudreach', line: 2000, glyph: '🌌', direction: 'up', limbSlots: 3,
    ritual: { cost: { amber: 200, clockwork: 100, lantern: 2000 } },
    sky: ['#1d1040', '#7a3f8c'], leaf: '#b58cff', ambient: ['✨', '🦉'],
    drops: [{ id: 'starfall', weight: 1 }, { id: 'honey', weight: 6 }],
    desc: 'Purple dusk, aurora curtains and the first true stars. The Stargazer Roost and the Observatory at 3,000 m.' },
  { id: 'starbough', index: 8, name: 'Starbough', line: 5000, glyph: '🌠', direction: 'up', limbSlots: 4,
    ritual: { cost: { starglass: 50, clockwork: 500, lantern: 5000 }, requiresSeason: 2 },
    sky: ['#02030d', '#1a1f4d'], leaf: '#e6e9ff', ambient: ['☄️', '✨'],
    drops: [{ id: 'starfall', weight: 1 }, { id: 'ore', weight: 4 }],
    desc: 'A black starfield with constellations and comet trails. Needs Season 3 or later. The Star Chart altar and Elder branch slots.' },
  { id: 'elder', index: 9, name: 'Elder Bough', line: 12000, glyph: '🌙', direction: 'up', limbSlots: 4,
    ritual: { cost: { starglass: 400, clockwork: 3000 } },
    sky: ['#050a2e', '#2b2f6b'], leaf: '#c8ffd4', ambient: ['🌙', '🌱'],
    drops: [{ id: 'starfall', weight: 2 }, { id: 'honey', weight: 5 }],
    desc: 'Deep navy, a second moon and floating seeds. Two extra annex slots and the Elder Sap.' },
  { id: 'worldcrown', index: 10, name: 'Worldcrown', line: 20000, glyph: '🌞', direction: 'up', limbSlots: 4,
    ritual: { cost: { starglass: 3000, lantern: 20000 } },
    sky: ['#ffd27a', '#ffe9c2'], leaf: '#ffe08a', ambient: ['🕊️', '☀️'],
    drops: [{ id: 'starfall', weight: 3 }, { id: 'ore', weight: 3 }],
    desc: 'Golden dawn above the clouds; the crown ornament sits here. The endgame cutscene and the Elder Crown.' },
]
