/** §14.1 Cosmetics catalog. Everything is a parameter set the scene reads; nothing has a stat effect. */
import type { CosmeticDef, BundleDef } from '../types'

export const cosmetics: CosmeticDef[] = [
  // ---- lantern colour ----
  { id: 'lc_amber', category: 'lantern_color', name: 'Amber', glyph: '🏮', desc: 'The default warm glow.', earnedBy: 'g14', params: { color: '#ffb547' } },
  { id: 'lc_moss', category: 'lantern_color', name: 'Moss', glyph: '🏮', desc: 'A soft green glow.', earnedBy: 'm_lantern_1k', params: { color: '#8bd36b' } },
  { id: 'lc_rose', category: 'lantern_color', name: 'Rose', glyph: '🏮', desc: 'A pink glow.', fireflyPrice: 80, params: { color: '#ff7eb3' } },
  { id: 'lc_teal', category: 'lantern_color', name: 'Lagoon', glyph: '🏮', desc: 'A cool teal glow.', fireflyPrice: 90, params: { color: '#4fd1c5' } },
  { id: 'lc_icewater', category: 'lantern_color', name: 'Icewater', glyph: '🏮', desc: 'Pale winter blue.', earnedBy: 'm_thaws_5', params: { color: '#9fe3ff' } },
  { id: 'lc_dye', category: 'lantern_color', name: 'Dyed', glyph: '🎨', desc: 'Any hue, dyed with Lacquer at the Kite Yard.', earnedBy: 'Kite Yard: 20 Lacquer per hue', params: { color: '#ffffff' } },
  // ---- lantern shape ----
  { id: 'ls_paper', category: 'lantern_shape', name: 'Paper', glyph: '🏮', desc: 'A rounded paper lantern.', earnedBy: 'm_lantern_100', params: { shape: 'paper' } },
  { id: 'ls_gourd', category: 'lantern_shape', name: 'Gourd', glyph: '🏮', desc: 'Bulbous and homely.', earnedBy: 'm_lantern_10k', params: { shape: 'gourd' } },
  { id: 'ls_bell', category: 'lantern_shape', name: 'Bell', glyph: '🔔', desc: 'A bell silhouette.', fireflyPrice: 120, params: { shape: 'bell' } },
  { id: 'ls_acorn', category: 'lantern_shape', name: 'Acorn', glyph: '🌰', desc: 'A capped, round little lantern.', fireflyPrice: 100, params: { shape: 'round' } },
  { id: 'ls_crystal', category: 'lantern_shape', name: 'Crystal', glyph: '💎', desc: 'Faceted; it refracts the glow.', price: 250, params: { shape: 'crystal' } },
  { id: 'ls_jelly', category: 'lantern_shape', name: 'Jellyfish', glyph: '🪼', desc: 'Trailing tendrils drift beneath it.', price: 250, params: { shape: 'jelly' } },
  // ---- lantern glow ----
  { id: 'lg_flicker', category: 'lantern_glow', name: 'Flicker', glyph: '🕯️', desc: 'Candle flicker.', earnedBy: 'm_codex_50', params: { glow: 'flicker' } },
  { id: 'lg_pulse', category: 'lantern_glow', name: 'Pulse-with-Thrum', glyph: '💓', desc: 'Every lantern pulses with the combo meter.', price: 300, params: { glow: 'pulse' } },
  { id: 'lg_swarm', category: 'lantern_glow', name: 'Firefly-swarm', glyph: '✨', desc: 'Fireflies orbit each lantern.', earnedBy: 'm_lantern_100k', params: { glow: 'swarm' } },
  { id: 'lg_golden', category: 'lantern_glow', name: 'Golden Keeper', glyph: '🌟', desc: 'A gold shimmer. Supporter Pack.', supporter: true, params: { glow: 'golden' } },
  { id: 'lg_ember', category: 'lantern_glow', name: 'Ember', glyph: '🔥', desc: 'A slow, breathing ember glow.', fireflyPrice: 150, params: { glow: 'flicker' } },
  { id: 'lg_moon', category: 'lantern_glow', name: 'Moonlit', glyph: '🌙', desc: 'A steady, silvery glow.', fireflyPrice: 180, params: { glow: 'steady' } },
  // ---- tree ----
  { id: 'tr_oak', category: 'tree', name: 'Oak', glyph: '🌳', desc: 'The tree as it grew.', starter: true, params: { bark: '#6b4a2e', leaf: '#5aa653', leafShape: 'round' } },
  { id: 'tr_autumn', category: 'tree', name: 'Autumn', glyph: '🍂', desc: 'Orange leaves and falling-leaf particles. Autumn medal.', earnedBy: 'Season Medal: Autumn (Turn 1)', params: { bark: '#5a3a22', leaf: '#e0702a', leafShape: 'round', petals: true } },
  { id: 'tr_winter', category: 'tree', name: 'Winter', glyph: '❄️', desc: 'Snow caps, blue light and icicle lanterns. Winter medal.', earnedBy: 'Season Medal: Winter (Turn 2)', params: { bark: '#4a4f5c', leaf: '#cfe6f2', leafShape: 'needle' } },
  { id: 'tr_spring', category: 'tree', name: 'Spring', glyph: '🌸', desc: 'Blossoms and bees. Spring medal.', earnedBy: 'Season Medal: Spring (Turn 3)', params: { bark: '#6b4a2e', leaf: '#ffb7d5', leafShape: 'blossom', petals: true } },
  { id: 'tr_summer', category: 'tree', name: 'Summer', glyph: '☀️', desc: 'Deep green under thunderheads. Summer medal.', earnedBy: 'Season Medal: Summer (Turn 4)', params: { bark: '#3f2a1a', leaf: '#1f6b3a', leafShape: 'round' } },
  { id: 'tr_birch', category: 'tree', name: 'Birch', glyph: '🌳', desc: 'White bark with black flecks.', earnedBy: 'm_season_3', params: { bark: '#e8e4dc', leaf: '#9ad65e', leafShape: 'birch' } },
  { id: 'tr_glowbark', category: 'tree', name: 'Glowbark', glyph: '🌳', desc: 'Bark veins glow at night.', earnedBy: 'm_rune_25', params: { bark: '#3a2f4a', leaf: '#5aa653', leafShape: 'round', glow: true } },
  { id: 'tr_elder', category: 'tree', name: 'Elder Oak', glyph: '🌳', desc: 'Gnarled, mossy, with giant leaves.', earnedBy: 'm_bough_elder', params: { bark: '#4d3a2a', leaf: '#3f8f4a', leafShape: 'elder' } },
  { id: 'tr_cherry', category: 'tree', name: 'Cherry Blossom', glyph: '🌸', desc: 'Pink leaves and a constant petal fall.', price: 600, params: { bark: '#5a3a3a', leaf: '#ffa6c9', leafShape: 'blossom', petals: true } },
  { id: 'tr_willow', category: 'tree', name: 'Ghost Willow', glyph: '🌫️', desc: 'Pale drooping leaves in mist.', price: 600, params: { bark: '#8a8f8a', leaf: '#cfe3d0', leafShape: 'willow' } },
  { id: 'tr_crystal', category: 'tree', name: 'Crystal Pine', glyph: '💎', desc: 'Translucent needles that catch the light.', price: 800, params: { bark: '#6d7fa3', leaf: '#bfe9ff', leafShape: 'crystal', glow: true } },
  { id: 'tr_night', category: 'tree', name: 'Nightbloom', glyph: '🌙', desc: 'Bioluminescent flowers open at night. Animated.', price: 900, params: { bark: '#2a2440', leaf: '#3b6b5a', leafShape: 'blossom', glow: true, animated: true } },
  { id: 'tr_maple', category: 'tree', name: 'Red Maple', glyph: '🍁', desc: 'Deep red leaves all year.', fireflyPrice: 300, params: { bark: '#5a3a22', leaf: '#c0392b', leafShape: 'round' } },
  { id: 'tr_silver', category: 'tree', name: 'Silver Fir', glyph: '🌲', desc: 'Blue-silver needles.', fireflyPrice: 350, params: { bark: '#4f4a45', leaf: '#8fb3b8', leafShape: 'needle' } },
  // ---- hat ----
  { id: 'hat_acorn', category: 'hat', name: 'Acorn Cap', glyph: '🌰', desc: 'On every Folk.', earnedBy: 'g47', params: { hat: 'acorn', color: '#8a5a2b' } },
  { id: 'hat_mushroom', category: 'hat', name: 'Mushroom Cap', glyph: '🍄', desc: 'A spotted red cap.', earnedBy: 'm_lodge_sapper_100', params: { hat: 'mushroom', color: '#d23c3c' } },
  { id: 'hat_straw', category: 'hat', name: 'Straw Hat', glyph: '👒', desc: 'Wide-brimmed and sunny.', fireflyPrice: 60, params: { hat: 'straw', color: '#e6c86a' } },
  { id: 'hat_leaf', category: 'hat', name: 'Leaf Cap', glyph: '🍃', desc: 'A single big leaf, worn like a beret.', fireflyPrice: 70, params: { hat: 'straw', color: '#6cc04a' } },
  { id: 'hat_bee', category: 'hat', name: 'Bee Suit', glyph: '🐝', desc: 'Stripes and a tiny veil.', earnedBy: 'm_blooms_10', params: { hat: 'bee', color: '#f2c94c' } },
  { id: 'hat_snail', category: 'hat', name: 'Snail Shell', glyph: '🐌', desc: 'A spiral shell hat.', earnedBy: 'Season Medal: Winter II (Turn 6)', params: { hat: 'snail', color: '#c9a27a' } },
  { id: 'hat_crown', category: 'hat', name: 'Tiny Crown', glyph: '👑', desc: 'A tiny gold crown on every Folk.', earnedBy: 'm_lodge_sapper_200', price: 200, params: { hat: 'crown', color: '#f5c542' } },
  { id: 'hat_wizard', category: 'hat', name: 'Wizard Hat', glyph: '🧙', desc: 'Tall, pointed and starry.', price: 200, params: { hat: 'wizard', color: '#5b4a9a' } },
  { id: 'hat_lanternhelm', category: 'hat', name: 'Lantern Helm', glyph: '⛑️', desc: 'A helmet with a lit lantern on top.', price: 300, params: { hat: 'lanternhelm', color: '#b8860b' } },
  // ---- chief ----
  { id: 'chief_regal', category: 'chief', name: 'Regal Cloak', glyph: '🧥', desc: 'A crimson cloak with gold trim for every Chief.', price: 350, params: { cloak: '#9b1c31', trim: '#f5c542' } },
  { id: 'chief_keeper', category: 'chief', name: "Keeper's Cloak", glyph: '🧥', desc: 'The Lantern-Keeper cloak. Supporter Pack.', supporter: true, params: { cloak: '#2f2a4a', trim: '#ffd27a' } },
  { id: 'chief_woven', category: 'chief', name: 'Woven Cloak', glyph: '🧥', desc: 'Plain fiber weave, hard-wearing.', fireflyPrice: 150, params: { cloak: '#8a7a55', trim: '#d8c27a' } },
  { id: 'chief_moss', category: 'chief', name: 'Moss Mantle', glyph: '🧥', desc: 'A green mantle grown, not sewn.', fireflyPrice: 180, params: { cloak: '#3f6b3a', trim: '#8bd36b' } },
  // ---- roof ----
  { id: 'roof_thatch', category: 'roof', name: 'Thatch', glyph: '🛖', desc: 'The default straw roof.', starter: true, params: { roof: 'thatch', color: '#c9a55a' } },
  { id: 'roof_slate', category: 'roof', name: 'Slate Tile', glyph: '🏠', desc: 'Grey slate tiles.', earnedBy: 'm_crew_kiln_100', params: { roof: 'slate', color: '#5c6670' } },
  { id: 'roof_mush', category: 'roof', name: 'Mushroom Cap', glyph: '🍄', desc: 'Spotted mushroom-cap roofs.', earnedBy: 'g50', params: { roof: 'mushroom', color: '#d23c3c' } },
  { id: 'roof_moss', category: 'roof', name: 'Moss-Grown', glyph: '🌿', desc: 'Roofs gone soft and green.', earnedBy: 'm_masterwork_50', params: { roof: 'moss', color: '#6b9a4a' } },
  { id: 'roof_hive', category: 'roof', name: 'Beehive Dome', glyph: '🐝', desc: 'Domed and honey-coloured.', earnedBy: 'm_blooms_50', params: { roof: 'hive', color: '#e0a83a' } },
  { id: 'roof_pagoda', category: 'roof', name: 'Pagoda', glyph: '⛩️', desc: 'Upturned eaves, lacquered red.', price: 300, params: { roof: 'pagoda', color: '#b03030' } },
  { id: 'roof_shell', category: 'roof', name: 'Shell', glyph: '🐚', desc: 'Spiral shells for roofs.', price: 300, params: { roof: 'shell', color: '#e8cfc0' } },
  { id: 'roof_glass', category: 'roof', name: 'Stained Glass', glyph: '🪟', desc: 'Glows with the lantern colour.', price: 450, params: { roof: 'glass', color: '#8fd9e8' } },
  { id: 'roof_bark', category: 'roof', name: 'Bark Shingle', glyph: '🪵', desc: 'Curled bark shingles.', fireflyPrice: 120, params: { roof: 'thatch', color: '#8a5a2b' } },
  { id: 'roof_leaf', category: 'roof', name: 'Leaf Thatch', glyph: '🍃', desc: 'Layered green leaves.', fireflyPrice: 140, params: { roof: 'moss', color: '#4fa24a' } },
  // ---- sky ----
  { id: 'sky_dawn', category: 'sky', name: 'Dawn Gold', glyph: '🌄', desc: 'The Canopy dawn, everywhere.', earnedBy: 'g24', params: { top: '#f4b860', bottom: '#8fbf7f', particle: 'none' } },
  { id: 'sky_twilight', category: 'sky', name: 'Twilight Violet', glyph: '🌆', desc: 'The Upper Trunk dusk.', earnedBy: 'm_line_upper', params: { top: '#5b4a7a', bottom: '#b8a6c9', particle: 'mist' } },
  { id: 'sky_star', category: 'sky', name: 'Starfield', glyph: '🌌', desc: 'A black sky full of stars.', earnedBy: 'm_setpiece_star_10', params: { top: '#02030d', bottom: '#1a1f4d', particle: 'stars', blend: 0.8 } },
  { id: 'sky_snow', category: 'sky', name: 'Gentle Snow', glyph: '🌨️', desc: 'Snow drifting past every bough.', earnedBy: 'm_thaws_25', params: { top: '#aab9c9', bottom: '#e8eef4', particle: 'snow' } },
  { id: 'sky_aurora', category: 'sky', name: 'Aurora', glyph: '🌈', desc: 'Curtains of green and violet light.', price: 400, params: { top: '#0b1a2e', bottom: '#2a4f5c', particle: 'aurora', blend: 0.8 } },
  { id: 'sky_petal', category: 'sky', name: 'Petal Rain', glyph: '🌸', desc: 'Petals fall forever.', price: 350, params: { top: '#f7c6d9', bottom: '#fff1f5', particle: 'petals' } },
  { id: 'sky_mist', category: 'sky', name: 'Bioluminescent Mist', glyph: '🌫️', desc: 'Glowing mist rolls between the limbs.', price: 500, params: { top: '#0f2a2e', bottom: '#1f5c5a', particle: 'mist', blend: 0.8 } },
  { id: 'sky_dusk', category: 'sky', name: 'Ember Dusk', glyph: '🌇', desc: 'Orange fading to plum.', fireflyPrice: 250, params: { top: '#ff8c42', bottom: '#4a2545', particle: 'fireflies' } },
  { id: 'sky_moon', category: 'sky', name: 'Moonrise', glyph: '🌕', desc: 'Silver-blue with a low moon.', fireflyPrice: 300, params: { top: '#1a2340', bottom: '#4a5a8a', particle: 'stars', blend: 0.7 } },
  // ---- tap ----
  { id: 'tap_sparks', category: 'tap', name: 'Sparks', glyph: '✨', desc: 'The default strike sparks.', starter: true, params: { particle: 'sparks', color: '#ffb547' } },
  { id: 'tap_sparks2', category: 'tap', name: 'Sparks+', glyph: '✨', desc: 'Bigger, brighter sparks.', earnedBy: 'm_taps_1k', params: { particle: 'sparks', color: '#ffd27a' } },
  { id: 'tap_petals', category: 'tap', name: 'Petals', glyph: '🌸', desc: 'Petals burst from every strike.', earnedBy: 'g16', params: { particle: 'petals', color: '#ffa6c9' } },
  { id: 'tap_notes', category: 'tap', name: 'Musical Notes', glyph: '🎵', desc: 'Notes float up from the bark.', earnedBy: 'm_taps_100k', params: { particle: 'notes', color: '#8fd9e8' } },
  { id: 'tap_gold', category: 'tap', name: 'Golden Sparks', glyph: '🌟', desc: 'Every strike sparks gold.', earnedBy: 'm_crit_1k', params: { particle: 'gold', color: '#f5c542' } },
  { id: 'tap_runes', category: 'tap', name: 'Runes', glyph: '🔯', desc: 'Glowing glyphs flash on the bark.', price: 150, params: { particle: 'runes', color: '#b58cff' } },
  { id: 'tap_ink', category: 'tap', name: 'Ink Splash', glyph: '🖋️', desc: 'Dark ink splashes.', price: 150, params: { particle: 'ink', color: '#2a2440' } },
  { id: 'tap_stars', category: 'tap', name: 'Tiny Stars', glyph: '⭐', desc: 'A scatter of tiny stars.', price: 200, params: { particle: 'stars', color: '#fff2a8' } },
  { id: 'tap_leaves', category: 'tap', name: 'Leaves', glyph: '🍃', desc: 'Leaves flutter off each strike.', fireflyPrice: 100, params: { particle: 'petals', color: '#6cc04a' } },
  { id: 'tap_bubbles', category: 'tap', name: 'Sap Bubbles', glyph: '🫧', desc: 'Amber bubbles rise and pop.', fireflyPrice: 120, params: { particle: 'sparks', color: '#ffe08a' } },
  // ---- meter (Thrum skin) ----
  { id: 'meter_wood', category: 'meter', name: 'Wood Ring', glyph: '🪵', desc: 'The default wooden Thrum ring.', starter: true, params: { style: 'wood' } },
  { id: 'meter_vine', category: 'meter', name: 'Vine', glyph: '🌿', desc: 'A vine that leafs out as the meter fills.', earnedBy: 'm_reso_100', params: { style: 'vine' } },
  { id: 'meter_clock', category: 'meter', name: 'Clockface', glyph: '🕰️', desc: 'Brass hands sweep the Thrum.', price: 200, params: { style: 'clock' } },
  { id: 'meter_stone', category: 'meter', name: 'Stone Ring', glyph: '🪨', desc: 'A carved stone ring.', fireflyPrice: 120, params: { style: 'wood', color: '#9aa3ad' } },
  { id: 'meter_moss', category: 'meter', name: 'Moss Ring', glyph: '🌱', desc: 'A ring of soft moss.', fireflyPrice: 140, params: { style: 'vine', color: '#8bd36b' } },
  // ---- crown ----
  { id: 'crown_vane', category: 'crown', name: 'Weathervane', glyph: '🐓', desc: 'A weathervane at the tip.', earnedBy: 'm_bough_crown', params: { ornament: 'vane', color: '#b8860b' } },
  { id: 'crown_chime', category: 'crown', name: 'Windchime', glyph: '🎐', desc: 'Chimes that ring in the wind. Autumn II medal.', earnedBy: 'Season Medal: Autumn II (Turn 5)', params: { ornament: 'chime', color: '#c9a27a' } },
  { id: 'crown_lantern', category: 'crown', name: 'Great Lantern', glyph: '🏮', desc: 'One enormous lantern at the tip.', price: 400, params: { ornament: 'lantern', color: '#ff8c42' } },
  { id: 'crown_crystal', category: 'crown', name: 'Crystal Spire', glyph: '💎', desc: 'A crystal spire catching the sky.', price: 500, params: { ornament: 'crystal', color: '#bfe9ff' } },
  { id: 'crown_kite', category: 'crown', name: 'Animated Kite', glyph: '🪁', desc: 'A kite tugging on its line.', price: 300, params: { ornament: 'kite', color: '#d23c3c' } },
  { id: 'crown_elder', category: 'crown', name: 'Elder Crown', glyph: '👑', desc: 'The crown of the Worldcrown.', earnedBy: 'm_season_20', params: { ornament: 'elder', color: '#ffd27a' } },
  { id: 'crown_flag', category: 'crown', name: 'Pennant', glyph: '🚩', desc: 'A long pennant streaming from the tip.', fireflyPrice: 150, params: { ornament: 'kite', color: '#4fd1c5' } },
  { id: 'crown_bell', category: 'crown', name: 'Tip Bell', glyph: '🔔', desc: 'A bronze bell at the very top.', fireflyPrice: 200, params: { ornament: 'chime', color: '#b87333' } },
  { id: 'kite_carp', category: 'crown', name: 'Carp Kite', glyph: '🎏', desc: 'Crafted at the Kite Yard: 50 Cord + 20 Lacquer + 60 Fireflies.', earnedBy: 'Kite Yard', params: { ornament: 'kite', color: '#ff7043' } },
  { id: 'kite_dragon', category: 'crown', name: 'Dragon Kite', glyph: '🐉', desc: 'Crafted at the Kite Yard: 50 Cord + 20 Lacquer + 120 Fireflies.', earnedBy: 'Kite Yard', params: { ornament: 'kite', color: '#2e8b57' } },
  { id: 'kite_guild', category: 'crown', name: 'Guild Banner', glyph: '🏴', desc: 'Crafted at the Kite Yard with one of 24 procedural emblems.', earnedBy: 'Kite Yard', params: { ornament: 'kite', color: '#5b4a9a' } },
  // ---- companion ----
  { id: 'pet_owl', category: 'companion', name: 'Owl', glyph: '🦉', desc: 'Hatched from the egg found at Landmark #30 after one Season.', earnedBy: 'm_season_1', params: { pet: 'owl', color: '#a58a6a' } },
  { id: 'pet_snail', category: 'companion', name: 'Snail', glyph: '🐌', desc: 'Slow, but always there.', fireflyPrice: 200, params: { pet: 'snail', color: '#c9a27a' } },
  { id: 'pet_swarm', category: 'companion', name: 'Firefly Swarm', glyph: '✨', desc: 'A swarm that follows your taps.', earnedBy: 'm_fireflies_1000', params: { pet: 'swarm', color: '#ffe08a' } },
  { id: 'pet_bee', category: 'companion', name: 'Bee', glyph: '🐝', desc: 'A fat, friendly bee.', earnedBy: 'm_setpiece_beehive_100', params: { pet: 'bee', color: '#f2c94c' } },
  { id: 'pet_cat', category: 'companion', name: 'Ash Cat', glyph: '🐈‍⬛', desc: 'Grey, sleepy and loyal.', earnedBy: 'm_streak_7', params: { pet: 'cat', color: '#6f6f7a' } },
  { id: 'pet_tabby', category: 'companion', name: 'Tabby Cat', glyph: '🐈', desc: 'Orange, curious and loud.', fireflyPrice: 220, params: { pet: 'cat', color: '#d9944a' } },
  { id: 'pet_fox', category: 'companion', name: 'Fox', glyph: '🦊', desc: 'Curls up by the stump at night.', price: 400, params: { pet: 'fox', color: '#e8702a' } },
  { id: 'pet_dragon', category: 'companion', name: 'Baby Dragon', glyph: '🐉', desc: 'Puffs smoke when you crit.', price: 700, params: { pet: 'dragon', color: '#2e8b57' } },
  { id: 'pet_deer', category: 'companion', name: 'Ghost Deer', glyph: '🦌', desc: 'Translucent, and only fully there at night.', price: 700, params: { pet: 'deer', color: '#cfe3d0' } },
  // ---- frame ----
  { id: 'frame_bark', category: 'frame', name: 'Bark', glyph: '🖼️', desc: 'The default Season Card frame.', starter: true, params: { style: 'bark', color: '#8a5a2b' } },
  { id: 'frame_rings', category: 'frame', name: 'Rings', glyph: '🖼️', desc: 'Stump rings around the card.', earnedBy: 'm_season_5', params: { style: 'rings', color: '#c9a55a' } },
  { id: 'frame_star', category: 'frame', name: 'Star', glyph: '🖼️', desc: 'Starglass corners.', earnedBy: 'm_starglass_1', params: { style: 'star', color: '#b7c6ff' } },
  { id: 'frame_greatring', category: 'frame', name: 'Great Ring', glyph: '🖼️', desc: 'The frame of ten Seasons.', earnedBy: 'm_season_10', params: { style: 'rings', color: '#ffd27a' } },
  { id: 'frame_astrolabe', category: 'frame', name: 'Astrolabe', glyph: '🖼️', desc: 'Brass constellations. Spring II medal.', earnedBy: 'Season Medal: Spring II (Turn 7)', params: { style: 'star', color: '#b8860b' } },
  { id: 'frame_gilded', category: 'frame', name: 'Gilded', glyph: '🖼️', desc: 'Gold leaf on every edge.', price: 200, params: { style: 'gilded', color: '#f5c542' } },
  { id: 'frame_aurora', category: 'frame', name: 'Animated Aurora', glyph: '🖼️', desc: 'Aurora light moves through the frame.', price: 300, params: { style: 'aurora', color: '#7fffd4' } },
  { id: 'frame_keeper', category: 'frame', name: "Keeper's Gold", glyph: '🖼️', desc: 'The golden nameplate frame. Supporter Pack.', supporter: true, params: { style: 'gilded', color: '#ffd27a' } },
  { id: 'frame_leaf', category: 'frame', name: 'Leafwork', glyph: '🖼️', desc: 'Woven leaves.', fireflyPrice: 100, params: { style: 'bark', color: '#6cc04a' } },
  { id: 'frame_moon', category: 'frame', name: 'Moonring', glyph: '🖼️', desc: 'A pale ring of moonlight.', fireflyPrice: 150, params: { style: 'rings', color: '#cfe6f2' } },
  // ---- title ----
  { id: 'title_cloudreacher', category: 'title', name: 'Cloudreacher', glyph: '🏷️', desc: 'Reached the Cloudreach line.', earnedBy: 'm_line_cloudreach', params: { text: 'Cloudreacher' } },
  { id: 'title_storm', category: 'title', name: 'Storm Whisperer', glyph: '🏷️', desc: 'Discharged the Lightning Rod ten times.', earnedBy: 'm_discharges_10', params: { text: 'Storm Whisperer' } },
  { id: 'title_loremaster', category: 'title', name: 'Loremaster', glyph: '🏷️', desc: 'Completed the Codex.', earnedBy: 'm_codex_100', params: { text: 'Loremaster' } },
  { id: 'title_kiteflyer', category: 'title', name: 'Kite-flyer', glyph: '🏷️', desc: 'Crafted a kite.', earnedBy: 'm_kite_1', params: { text: 'Kite-flyer' } },
  { id: 'title_keeper', category: 'title', name: 'Keeper', glyph: '🏷️', desc: 'Lantern-Keeper. Supporter Pack.', supporter: true, params: { text: 'Keeper' } },
  { id: 'title_explorer', category: 'title', name: 'Explorer', glyph: '🏷️', desc: 'Summer II medal.', earnedBy: 'Season Medal: Summer II (Turn 8)', params: { text: 'Explorer' } },
  { id: 'title_giantfriend', category: 'title', name: 'Giantfriend', glyph: '🏷️', desc: 'Opened the Worldcrown.', earnedBy: 'm_bough_worldcrown', params: { text: 'Giantfriend' } },
  { id: 'title_sapling', category: 'title', name: 'Sapling', glyph: '🏷️', desc: 'Small, but growing.', fireflyPrice: 60, params: { text: 'Sapling' } },
  { id: 'title_lanternlit', category: 'title', name: 'Lantern-lit', glyph: '🏷️', desc: 'Never in the dark.', fireflyPrice: 100, params: { text: 'Lantern-lit' } },
]

/** Themed sets at ~25% off. Rotate weekly on the featured shelf; nothing is ever removed. */
export const bundles: BundleDef[] = [
  { id: 'bundle_cherry', name: 'Cherry Blossom Grove', glyph: '🌸', items: ['tr_cherry', 'sky_petal', 'tap_petals', 'lc_rose', 'ls_paper'], price: 1000, desc: 'Cherry Blossom tree, Petal Rain sky, Petals strikes and pink paper lanterns.' },
  { id: 'bundle_deepsea', name: 'Deep Sea', glyph: '🪼', items: ['ls_jelly', 'sky_mist', 'roof_shell', 'hat_snail'], price: 900, desc: 'Jellyfish lanterns, Bioluminescent Mist, Shell roofs and the Snail Shell hat.' },
  { id: 'bundle_clockwork', name: 'Clockwork Court', glyph: '🕰️', items: ['meter_clock', 'lc_amber', 'hat_crown', 'roof_pagoda', 'tap_runes'], price: 800, desc: 'Clockface meter, brass-amber lanterns, Tiny Crowns, Pagoda roofs and Rune strikes.' },
  { id: 'bundle_observatory', name: 'Midnight Observatory', glyph: '🔭', items: ['sky_star', 'crown_crystal', 'pet_owl', 'tap_stars'], price: 1000, desc: 'Starfield sky, Crystal Spire, an Owl and Tiny Stars.' },
]
