/** §4 Resources — tier 0 raws and tier 1-4 crafted goods. Meta currencies live in state. */
import type { ResourceDef } from '../types'

export const resources: ResourceDef[] = [
  // ---- tier 0: raws ----
  { id: 'sap', name: 'Sap', glyph: '💧', tier: 0, worth: 1, color: '#ffb547', base: true,
    desc: 'The lifeblood of the tree. Strike the trunk or let Sappers tap it for you; every drop can GROW the spire.',
    source: 'Sap comes from Strikes and Sapper Lodges — hire a Sapper' },
  { id: 'bark', name: 'Bark', glyph: '🪵', tier: 0, worth: 2, color: '#b07a4a',
    desc: 'Curls of bark peeled from the trunk. The Sawmill turns it into Planks.',
    source: 'Bark comes from Peelers — hire a Peeler Lodge' },
  { id: 'stone', name: 'Stone', glyph: '🪨', tier: 0, worth: 3, color: '#9aa3ad',
    desc: 'Pale stone dug from between the roots. Bricks and Glass start here.',
    source: 'Stone comes from Diggers — open Bough 2 (Roots)' },
  { id: 'fiber', name: 'Fiber', glyph: '🧵', tier: 0, worth: 4, color: '#d8c27a',
    desc: 'Long leaf fibres combed from the canopy. Woven into Cord at the Ropewalk.',
    source: 'Fiber comes from Weavers — open Bough 3 (Canopy)' },
  { id: 'honey', name: 'Honey', glyph: '🍯', tier: 0, worth: 12, color: '#f0a020',
    desc: 'Golden and slow. Shaken from wild hives, or gathered by Beekeepers at the Apiary.',
    source: 'Honey comes from Beehive Shakes and the Apiary annex — sprout a limb on the Canopy' },
  { id: 'ore', name: 'Ore', glyph: '⛏️', tier: 0, worth: 20, color: '#7c8aa0',
    desc: 'Veins of ore glinting in the deep roots. The Forge smelts it into Ingots.',
    source: 'Ore comes from Miners — open Bough 5 (Deep Roots)' },
  { id: 'starfall', name: 'Starfall', glyph: '⭐', tier: 0, worth: 2000, color: '#fff2a8',
    desc: 'A fragment of a fallen star, still warm. Only the Observatory knows what to do with it.',
    source: 'Starfall comes from Falling Stars (Crown) and the Stargazer Roost — open Bough 7 (Cloudreach)' },
  // ---- tier 1 ----
  { id: 'resin', name: 'Resin', glyph: '🫙', tier: 1, worth: 20, color: '#e0a040',
    desc: 'Sap boiled down at the Kiln. The first crafted good and the glue of every chain.',
    source: 'Resin is made at the Kiln — build it at the stump and tap it to craft' },
  { id: 'plank', name: 'Plank', glyph: '🪚', tier: 1, worth: 24, color: '#c9955a',
    desc: 'Bark pressed and cut at the Sawmill. Beams, lodges and the Roots Ritual are priced in Planks.',
    source: 'Planks are made at the Sawmill — GROW to 20 m and build it' },
  { id: 'cord', name: 'Cord', glyph: '🪢', tier: 1, worth: 64, color: '#b8a15c',
    desc: 'Fiber twisted at the Ropewalk. Bridges, kites and lanterns all hang from it.',
    source: 'Cord is made at the Ropewalk — GROW to 80 m on the Canopy and build it' },
  { id: 'brick', name: 'Brick', glyph: '🧱', tier: 1, worth: 120, color: '#c0563a',
    desc: 'Stone bound with Resin and fired at the Brickyard.',
    source: 'Bricks are made at the Brickyard — open Bough 2 (Roots) and build it' },
  // ---- tier 2 ----
  { id: 'beam', name: 'Beam', glyph: '🪵', tier: 2, worth: 480, color: '#8a5a2b',
    desc: 'Planks laminated with Resin at the Beamworks. Limbs, Rituals and the Foreman\'s Bell are priced in Beams.',
    source: 'Beams are made at the Beamworks — GROW to 40 m and build it' },
  { id: 'glass', name: 'Glass', glyph: '🔮', tier: 2, worth: 210, color: '#8fd9e8',
    desc: 'Stone and Resin fused in the Glasshouse. Lanterns and the Rune of Thrum need it.',
    source: 'Glass is made at the Glasshouse — open Bough 2 (Roots) and build it' },
  { id: 'lacquer', name: 'Lacquer', glyph: '🎨', tier: 2, worth: 480, color: '#b03060',
    desc: 'Resin, Cord and Honey cured into a deep gloss. Discovered in the Crucible.',
    source: 'Lacquer is made at the Lacquery — discover the recipe in the Crucible' },
  { id: 'ingot', name: 'Ingot', glyph: '⚙️', tier: 2, worth: 1400, color: '#a9b4c2',
    desc: 'Ore smelted in a Brick-lined Forge. Clockwork and the Crown Ritual are priced in Ingots.',
    source: 'Ingots are made at the Forge — open Bough 5 (Deep Roots) and build it' },
  // ---- tier 3 ----
  { id: 'lantern', name: 'Lantern', glyph: '🏮', tier: 3, worth: 4000, color: '#ff8c42',
    desc: 'Glass, Lacquer and Cord. Every 100 crafted lights another bough. Discovered in the Crucible.',
    source: 'Lanterns are made at the Lanternry — discover the recipe and build it at 250 m' },
  { id: 'amber', name: 'Amber', glyph: '🟠', tier: 3, worth: 2400, color: '#ffa000',
    desc: 'Resin and Honey aged in the Amber Vault. Buys Stargazers and the Rune of Time.',
    source: 'Amber is made at the Amber Vault — discover the recipe and build it at 300 m' },
  { id: 'clockwork', name: 'Clockwork', glyph: '⏱️', tier: 3, worth: 20000, color: '#d4a017',
    desc: 'Ingots, Cord and Lacquer assembled into ticking mechanisms. Discovered in the Crucible.',
    source: 'Clockwork is made at the Clockworks — discover the recipe and build it at 1,000 m on the Crown' },
  // ---- tier 4 ----
  { id: 'starglass', name: 'Starglass', glyph: '💠', tier: 4, worth: 65000, color: '#b7c6ff',
    desc: 'Glass, Amber and a fallen star, fused in the Observatory. The currency of the highest boughs.',
    source: 'Starglass is made at the Observatory — discover the recipe and build it at 3,000 m on Cloudreach' },
]
