/** §10.2 The authored Season-1 lane (63 goals) and the persistent Legacy lane. */
import type { WaystoneGoalDef, Condition } from '../types'

type G = Omit<WaystoneGoalDef, 'id'>
const rows: G[] = [
  /* 1 */ { name: 'Strike the trunk 5 times', cond: { kind: 'strikes', min: 5 }, reward: { resources: { sap: 5 } }, tutorial: true, tab: 'grow', target: 'trunk' },
  /* 2 */ { name: 'GROW once', cond: { kind: 'grows', min: 1 }, reward: { fireflies: 5 }, tutorial: true, tab: 'grow', target: 'grow' },
  /* 3 */ { name: 'Hire a Sapper (15 Sap)', cond: { kind: 'producer', id: 'sapper', min: 1 }, reward: { fireflies: 5 }, tutorial: true, tab: 'folk', target: 'sapper' },
  /* 4 */ { name: 'Own 3 Sappers', cond: { kind: 'producer', id: 'sapper', min: 3 }, reward: { fireflies: 5 }, tutorial: true, tab: 'folk', target: 'sapper' },
  /* 5 */ { name: 'Build the Kiln (40 Sap)', cond: { kind: 'workshop', id: 'kiln' }, reward: { fireflies: 5 }, tutorial: true, tab: 'craft', target: 'kiln' },
  /* 6 */ { name: 'Hand-craft 5 Resin', cond: { kind: 'handcrafts', station: 'kiln', min: 5 }, reward: { fireflies: 5 }, tutorial: true, tab: 'craft', target: 'kiln' },
  /* 7 */ { name: 'Hire the Kiln Foreman (25 Resin)', cond: { kind: 'producer', id: 'kiln_crew', min: 1 }, reward: { fireflies: 15, chest: 'bark' }, tutorial: true, tab: 'craft', target: 'kiln' },
  /* 8 */ { name: 'Hire a Peeler (60 Sap)', cond: { kind: 'producer', id: 'peeler', min: 1 }, reward: { fireflies: 5 }, tab: 'folk', target: 'peeler' },
  /* 9 */ { name: 'GROW to 20 m', cond: { kind: 'height', min: 20 }, reward: { fireflies: 5 }, tab: 'grow', target: 'grow' },
  /* 10 */ { name: 'Build the Sawmill (30 Bark)', cond: { kind: 'workshop', id: 'sawmill' }, reward: { fireflies: 50, landmark: 'lm_bridge' }, tab: 'craft', target: 'sawmill' },
  /* 11 */ { name: 'Fill the Thrum ring (first Resonance)', cond: { kind: 'resonances', min: 1 }, reward: { fireflies: 10 }, tutorial: true, tab: 'grow', target: 'trunk' },
  /* 12 */ { name: 'Hire the Sawmill Foreman (25 Plank)', cond: { kind: 'producer', id: 'sawmill_crew', min: 1 }, reward: { fireflies: 15, chest: 'bark' }, tab: 'craft', target: 'sawmill' },
  /* 13 */ { name: 'Sapper Lodge level 10', cond: { kind: 'producer', id: 'sapper', min: 10 }, reward: { fireflies: 10 }, tab: 'folk', target: 'sapper' },
  /* 14 */ { name: 'Carve Rune of Sap I (10 Resin)', cond: { kind: 'rune', id: 'rune_sap', min: 1 }, reward: { fireflies: 10, cosmetic: 'lc_amber' }, tab: 'grow', target: 'rune_sap' },
  /* 15 */ { name: 'GROW to 30 m (Roots line)', cond: { kind: 'height', min: 30 }, reward: { fireflies: 5 }, tab: 'grow', target: 'grow' },
  /* 16 */ { name: 'Ritual: Bough 2 Roots', cond: { kind: 'bough', id: 'roots' }, reward: { chest: 'amber', glimmer: 20, cosmetic: 'tap_petals' }, tab: 'grow', target: 'ritual:roots' },
  /* 17 */ { name: 'Hire a Digger (6 Resin)', cond: { kind: 'producer', id: 'digger', min: 1 }, reward: { fireflies: 5 }, tab: 'folk', target: 'digger' },
  /* 18 */ { name: 'Build the Brickyard (20 Resin + 20 Stone)', cond: { kind: 'workshop', id: 'brickyard' }, reward: { fireflies: 5 }, tab: 'craft', target: 'brickyard' },
  /* 19 */ { name: 'Hire the Brickyard Foreman (25 Brick)', cond: { kind: 'producer', id: 'brickyard_crew', min: 1 }, reward: { fireflies: 15 }, tab: 'craft', target: 'brickyard' },
  /* 20 */ { name: 'GROW to 40 m', cond: { kind: 'height', min: 40 }, reward: { fireflies: 50, landmark: 'lm_birdhouse' }, tab: 'grow', target: 'grow' },
  /* 21 */ { name: 'Build the Beamworks (30 Plank + 10 Resin)', cond: { kind: 'workshop', id: 'beamworks' }, reward: { fireflies: 5 }, tab: 'craft', target: 'beamworks' },
  /* 22 */ { name: 'Hire the Beamworks Foreman (15 Beam)', cond: { kind: 'producer', id: 'beamworks_crew', min: 1 }, reward: { fireflies: 15, chest: 'bark' }, tab: 'craft', target: 'beamworks' },
  /* 23 */ { name: 'Carve Rune of Bark I (10 Plank)', cond: { kind: 'rune', id: 'rune_bark', min: 1 }, reward: { fireflies: 10 }, tab: 'grow', target: 'rune_bark' },
  /* 24 */ { name: 'GROW to 60 m (Canopy line)', cond: { kind: 'height', min: 60 }, reward: { fireflies: 10, cosmetic: 'sky_dawn' }, tab: 'grow', target: 'grow' },
  /* 25 */ { name: 'Ritual: Bough 3 Canopy', cond: { kind: 'bough', id: 'canopy' }, reward: { chest: 'amber', glimmer: 20 }, tab: 'grow', target: 'ritual:canopy' },
  /* 26 */ { name: 'Hire a Weaver (10 Plank)', cond: { kind: 'producer', id: 'weaver', min: 1 }, reward: { fireflies: 5 }, tab: 'folk', target: 'weaver' },
  /* 27 */ { name: 'Build the Ropewalk (20 Plank)', cond: { kind: 'workshop', id: 'ropewalk' }, reward: { fireflies: 5 }, tab: 'craft', target: 'ropewalk' },
  /* 28 */ { name: 'Peeler Lodge level 10', cond: { kind: 'producer', id: 'peeler', min: 10 }, reward: { fireflies: 10 }, tab: 'folk', target: 'peeler' },
  /* 29 */ { name: 'Hire the Ropewalk Foreman (25 Cord)', cond: { kind: 'producer', id: 'ropewalk_crew', min: 1 }, reward: { fireflies: 15 }, tab: 'craft', target: 'ropewalk' },
  /* 30 */ { name: 'Sprout a limb (10 Beam) and build the Apiary', cond: { kind: 'annex', id: 'apiary' }, reward: { fireflies: 50, landmark: 'lm_owl' }, tab: 'grow', target: 'annex:apiary' },
  /* 31 */ { name: 'Hire a Beekeeper (5 Cord)', cond: { kind: 'producer', id: 'beekeeper', min: 1 }, reward: { fireflies: 5 }, tab: 'folk', target: 'beekeeper' },
  /* 32 */ { name: 'Build the Glasshouse (15 Brick)', cond: { kind: 'workshop', id: 'glasshouse' }, reward: { fireflies: 5 }, tab: 'craft', target: 'glasshouse' },
  /* 33 */ { name: 'Hire the Glasshouse Foreman (15 Glass)', cond: { kind: 'producer', id: 'glasshouse_crew', min: 1 }, reward: { fireflies: 15, chest: 'bark' }, tab: 'craft', target: 'glasshouse' },
  /* 34 */ { name: 'Discover Lacquer in the Crucible', cond: { kind: 'discovered', recipe: 'lacquer' }, reward: { fireflies: 40 }, tab: 'craft', target: 'crucible:lacquer' },
  /* 35 */ { name: 'Build the Lacquery and hire its Foreman (15 Lacquer)', cond: { kind: 'producer', id: 'lacquery_crew', min: 1 }, reward: { fireflies: 15 }, tab: 'craft', target: 'lacquery' },
  /* 36 */ { name: 'Sapper Lodge level 25 (x2)', cond: { kind: 'producer', id: 'sapper', min: 25 }, reward: { fireflies: 10 }, tab: 'folk', target: 'sapper' },
  /* 37 */ { name: "Carve Foreman's Bell I (10 Beam)", cond: { kind: 'rune', id: 'rune_bell', min: 1 }, reward: { fireflies: 10 }, tab: 'grow', target: 'rune_bell' },
  /* 38 */ { name: 'GROW to 200 m (Upper Trunk line)', cond: { kind: 'height', min: 200 }, reward: { fireflies: 10 }, tab: 'grow', target: 'grow' },
  /* 39 */ { name: 'Kiln crew 10', cond: { kind: 'producer', id: 'kiln_crew', min: 10 }, reward: { fireflies: 10 }, tab: 'craft', target: 'kiln' },
  /* 40 */ { name: 'Ritual: Bough 4 Upper Trunk', cond: { kind: 'bough', id: 'upper' }, reward: { chest: 'amber', glimmer: 20, fireflies: 50, landmark: 'lm_chimes' }, tab: 'grow', target: 'ritual:upper' },
  /* 41 */ { name: 'GROW to 250 m and build the Lanternry (20 Beam + 10 Glass)', cond: { kind: 'workshop', id: 'lanternry' }, reward: { fireflies: 5 }, tab: 'craft', target: 'lanternry' },
  /* 42 */ { name: 'Hire the Lanternry Foreman (10 Lantern)', cond: { kind: 'producer', id: 'lanternry_crew', min: 1 }, reward: { fireflies: 15 }, tab: 'craft', target: 'lanternry' },
  /* 43 */ { name: 'Catch a set-piece (beehive, woodpecker or acorn)', cond: { kind: 'setpieces', min: 1 }, reward: { fireflies: 20 }, tab: 'grow', target: 'trunk' },
  /* 44 */ { name: 'Discover Amber in the Crucible', cond: { kind: 'discovered', recipe: 'amber' }, reward: { fireflies: 60 }, tab: 'craft', target: 'crucible:amber' },
  /* 45 */ { name: 'Build the Amber Vault (300 m) and hire its Foreman (10 Amber)', cond: { kind: 'producer', id: 'ambervault_crew', min: 1 }, reward: { fireflies: 15, chest: 'bark' }, tab: 'craft', target: 'ambervault' },
  /* 46 */ { name: 'Carve Rune of Sap III', cond: { kind: 'rune', id: 'rune_sap', min: 3 }, reward: { fireflies: 10 }, tab: 'grow', target: 'rune_sap' },
  /* 47 */ { name: 'Sapper Lodge level 50 (the Chief appears)', cond: { kind: 'producer', id: 'sapper', min: 50 }, reward: { fireflies: 10, cosmetic: 'hat_acorn' }, tab: 'folk', target: 'sapper' },
  /* 48 */ { name: 'Craft 100 Lanterns (the Trunk lights up)', cond: { kind: 'lanterns', min: 100 }, reward: { fireflies: 25, cosmetic: 'ls_paper' }, tab: 'craft', target: 'lanternry' },
  /* 49 */ { name: 'GROW to 400 m (Deep Roots line)', cond: { kind: 'height', min: 400 }, reward: { fireflies: 10 }, tab: 'grow', target: 'grow' },
  /* 50 */ { name: 'Ritual: Bough 5 Deep Roots', cond: { kind: 'bough', id: 'deeproots' }, reward: { chest: 'amber', glimmer: 20, fireflies: 50, landmark: 'lm_mushrooms', cosmetic: 'roof_mush' }, tab: 'grow', target: 'ritual:deeproots' },
  /* 51 */ { name: 'Hire a Miner (4 Beam)', cond: { kind: 'producer', id: 'miner', min: 1 }, reward: { fireflies: 5 }, tab: 'folk', target: 'miner' },
  /* 52 */ { name: 'Build the Forge and hire its Foreman (15 Ingot)', cond: { kind: 'producer', id: 'forge_crew', min: 1 }, reward: { fireflies: 15, chest: 'bark' }, tab: 'craft', target: 'forge' },
  /* 53 */ { name: 'Carve Rune of Ore I (5 Ingot)', cond: { kind: 'rune', id: 'rune_ore', min: 1 }, reward: { fireflies: 10 }, tab: 'grow', target: 'rune_ore' },
  /* 54 */ { name: 'Craft 300 Lanterns (three boughs lit)', cond: { kind: 'lanterns', min: 300 }, reward: { fireflies: 25 }, tab: 'craft', target: 'lanternry' },
  /* 55 */ { name: 'Sprout a second limb and build the Kite Yard (25 Cord)', cond: { kind: 'annex', id: 'kite_yard' }, reward: { fireflies: 20 }, tab: 'grow', target: 'annex:kite_yard' },
  /* 56 */ { name: 'Craft a Carp Kite at the Kite Yard', cond: { kind: 'kites', min: 1 }, reward: { cosmetic: 'kite_carp' }, tab: 'wardrobe', target: 'kite_carp' },
  /* 57 */ { name: 'Carve Rune of Roots I (5 Lantern)', cond: { kind: 'rune', id: 'rune_roots', min: 1 }, reward: { fireflies: 10 }, tab: 'grow', target: 'rune_roots' },
  /* 58 */ { name: 'Reach 3 Rings (the Season Turn button appears)', cond: { kind: 'rings', min: 3 }, reward: { fireflies: 25 }, tab: 'rings', target: 'turn' },
  /* 59 */ { name: 'Kiln crew 50', cond: { kind: 'producer', id: 'kiln_crew', min: 50 }, reward: { fireflies: 10 }, tab: 'craft', target: 'kiln' },
  /* 60 */ { name: 'Reach 5 Rings (Turn recommended)', cond: { kind: 'rings', min: 5 }, reward: { fireflies: 50, landmark: 'lm_flags' }, tab: 'rings', target: 'turn' },
  /* 61 */ { name: 'GROW to 800 m (Crown line)', cond: { kind: 'height', min: 800 }, reward: { fireflies: 10 }, optional: true, tab: 'grow', target: 'grow' },
  /* 62 */ { name: 'Ritual: Bough 6 Crown', cond: { kind: 'bough', id: 'crown' }, reward: { chest: 'amber', glimmer: 20 }, optional: true, tab: 'grow', target: 'ritual:crown' },
  /* 63 */ { name: 'Turn the Season', cond: { kind: 'seasons', min: 1 }, reward: { fireflies: 100, glimmer: 10 }, tab: 'rings', target: 'turn' },
]

export const waystoneSeason1: WaystoneGoalDef[] = rows.map((g, i) => ({ id: `g${i + 1}`, ...g }))

const L = (id: string, name: string, cond: Condition) => ({ id, name, cond })
/** Persistent lane shown on the "then:" line when the Season lane's next goal is far away. */
export const legacyLane: { id: string; name: string; cond: Condition }[] = [
  L('lg_season_1', 'Turn the Season once', { kind: 'seasons', min: 1 }),
  L('lg_codex_25', 'Codex 25%', { kind: 'codex', pct: 25 }),
  L('lg_lantern_100', '100 Lanterns crafted (lifetime)', { kind: 'lanterns', min: 100, lifetime: true }),
  L('lg_cosmetics_5', 'Own 5 cosmetics', { kind: 'cosmetics', min: 5 }),
  L('lg_rings_25', '25 lifetime Rings', { kind: 'lifetimeRings', min: 25 }),
  L('lg_season_3', 'Three Seasons turned', { kind: 'seasons', min: 3 }),
  L('lg_codex_50', 'Codex 50%', { kind: 'codex', pct: 50 }),
  L('lg_lantern_1k', '1,000 Lanterns crafted (lifetime)', { kind: 'lanterns', min: 1000, lifetime: true }),
  L('lg_cosmetics_10', 'Own 10 cosmetics', { kind: 'cosmetics', min: 10 }),
  L('lg_season_5', 'Five Seasons turned', { kind: 'seasons', min: 5 }),
  L('lg_rings_100', '100 lifetime Rings', { kind: 'lifetimeRings', min: 100 }),
  L('lg_codex_75', 'Codex 75%', { kind: 'codex', pct: 75 }),
  L('lg_cosmetics_20', 'Own 20 cosmetics', { kind: 'cosmetics', min: 20 }),
  L('lg_season_10', 'Ten Seasons turned (Great Ring)', { kind: 'seasons', min: 10 }),
  L('lg_lantern_10k', '10,000 Lanterns crafted (lifetime)', { kind: 'lanterns', min: 10000, lifetime: true }),
  L('lg_rings_500', '500 lifetime Rings', { kind: 'lifetimeRings', min: 500 }),
  L('lg_codex_100', 'Codex complete', { kind: 'codex', pct: 100 }),
  L('lg_cosmetics_30', 'Own 30 cosmetics', { kind: 'cosmetics', min: 30 }),
  L('lg_season_20', 'Twenty Seasons turned (Elder Crown)', { kind: 'seasons', min: 20 }),
  L('lg_rings_1000', '1,000 lifetime Rings', { kind: 'lifetimeRings', min: 1000 }),
  L('lg_lantern_100k', '100,000 Lanterns crafted (lifetime)', { kind: 'lanterns', min: 100000, lifetime: true }),
]
